name: Release Builds

on:
  release:
    types: [created]

env:
  VULTR_REGISTRY: sjc.vultrcr.com
  VULTR_IMAGE_NAME: seven/lucky-tgbot
  GHCR_IMAGE_NAME: realsunyz/lucky-tgbot

jobs:
  docker-release:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in to Vultr Container Registry
        id: vultr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.VULTR_REGISTRY }}
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_PASSWORD }}

      - name: Log in to GitHub Container Registry
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:latest
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:latest-${{ github.event.release.tag_name }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest-${{ github.event.release.tag_name }}

      - name: Generate Artifact Attestation (OCI Referrers)
        id: attest
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}
          subject-digest: ${{ steps.image.outputs.digest }}
          push-to-registry: true
